### PR TITLE
[#6627] deps wagtail3

### PR DESCRIPTION
**Pull request by phillimorland**
Backup database before testing just in case. will branch off this for the wagtail4 update

### CODE REVIEW

**Comment by Rineee** [comment]
@phillimorland I get an error

```
  Applying apps_forms.0009_alter_formfield... OK
  Applying apps_home.0058_alter_streamfield_field...Traceback (most recent call last):
  File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: CHECK constraint failed: (JSON_VALID("body_de") OR "body_de" IS NULL)
```

But maybe there is sth wrong with my db, I think I have not worked on it for ages..

**Comment by Rineee** [comment]
> @phillimorland I get an error
> 
> ```
>   Applying apps_forms.0009_alter_formfield... OK
>   Applying apps_home.0058_alter_streamfield_field...Traceback (most recent call last):
>   File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
>     return self.cursor.execute(sql, params)
>   File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
>     return Database.Cursor.execute(self, query, params)
> sqlite3.IntegrityError: CHECK constraint failed: (JSON_VALID("body_de") OR "body_de" IS NULL)
> ```
> 
> But maybe there is sth wrong with my db, I think I have not worked on it for ages..

Still get that error with an older db, maybe you could check on yours @khamui ?

**Comment by phillimorland** [comment]
@Rineee odd, do you get it with an empty database?

**Comment by khamui** [comment]
> > @phillimorland I get an error
> > ```
> >   Applying apps_forms.0009_alter_formfield... OK
> >   Applying apps_home.0058_alter_streamfield_field...Traceback (most recent call last):
> >   File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
> >     return self.cursor.execute(sql, params)
> >   File "/home/rine/digitalstrategie/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
> >     return Database.Cursor.execute(self, query, params)
> > sqlite3.IntegrityError: CHECK constraint failed: (JSON_VALID("body_de") OR "body_de" IS NULL)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But maybe there is sth wrong with my db, I think I have not worked on it for ages..
> 
> Still get that error with an older db, maybe you could check on yours @khamui ?

@Rineee no errors for me

**Pull request merged**
