### PR TITLE
[5345] forms/validation: small adjustments to match styleguide

### PR DESCRIPTION
**Pull request by khamui**

### CODE REVIEW

**Comment by khamui** [comment]
sorry set to wip, because the messages themselves differ as well. Will have another look

**Comment by khamui** [comment]
couldn't find where to change the wording of the error message. But fixed some other small style issues to match the styleguide.

**Comment by phillimorland** [comment]
@khamui I think the error messages are set by django forms so would need to be overwritten I guess, is that right @fuzzylogic2000 ?

**Comment by khamui** [comment]
ah just saw there is a different task for it. so this is ready to be reviewed then!

**Comment by fuzzylogic2000** [comment]
> @khamui I think the error messages are set by django forms so would need to be overwritten I guess, is that right @fuzzylogic2000 ?

@phillimorland Yes, I think you are right. But as we only have the German wording, we can just overwrite the translation. :)

**Review by fuzzylogic2000 — APPROVED** [review]
Looks good! You are not working in this PR anymore and we can merge, right?

**Pull request merged**
