### PR TITLE
Translations: added missing translations in participation form

### LINKED ISSUE #238: Contact form English language instead of German
**URL:** https://digitalstrategie-dev.liqd.net/kontakt/
**user:** visitor
**expected behaviour:** German language
**behaviour:** It says "*Required fields"
**important screensize:** desktop
**device & browser:** macbook: firefox, safari

**Comment/Question:** 

Screenshot?

grafik

### PR DESCRIPTION
**Pull request by sabinammm**
Fixes #238
In the first commit, linebreaks were taken out of a blocktrans because these show up in the po-translation files.

### CODE REVIEW

**Review by phillimorland — COMMENTED** [review]
@sabinammm looking good! however I changed the form.html adding email tag so not sure if that will mean these will need re-doing? maybe we should wait till after that's merged and do a rebase and see?

**Comment by sabinammm** [comment]
> @sabinammm looking good! however I changed the form.html adding email tag so not sure if that will mean these will need re-doing? maybe we should wait till after that's merged and do a rebase and see?

Yes, thanks for the heads-up. Then we should probably just wait :+1:

**Comment by phillimorland** [comment]
@sabinammm the footer pull request hasn't been reviewed or merged yet, you're tagged in review there so have a look and if good merge, after that, this one can be rebased and you may have to redo some translations then tag me for review

**Review by fuzzylogic2000 — COMMENTED** [review]
Nice! 
I rebased it again after merge and added last translation.

**Pull request merged**
