### PR TITLE
Jd 2023 10 search result title

### PR DESCRIPTION
**Pull request by goapunk**
fixes various issues with the search

### CODE REVIEW

**Review by philli-m — CHANGES_REQUESTED** [review]
Looking good, just slight issue, when I try to change the language when I am on the search results page I get the following error 
```
RequestError(400, 'x_content_parse_exception', '[multi_match] unknown token [VALUE_NULL] after [query]')
```

**Comment by goapunk** [comment]
@philli-m should be fixed by #908

**Comment by goapunk** [comment]
@m4ra @philli-m I also added the elasticsearch update. Once this is merged we also need to merge https://github.com/liqd/admin/pull/651/files

**Review by philli-m — APPROVED** [review]
looks good and didn't manage to trigger any errors :)

**Pull request merged**
